services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  python_app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: python_app_container
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
      MYSQL_DATABASE: test_db
    depends_on:
      - mysql

volumes:
  mysql_data: