# Use the official Python image from the Docker Hub
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app



# Install any needed packages specified in requirements.txt
RUN pip install  mysql-connector-python  --upgrade

CMD ["echo", "Hello world"]
