# Use la imagen oficial de Python
# FROM python:3.9-slim

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar los archivos del proyecto al contenedor
COPY ./app /app

# Instalar dependencias
# RUN pip install mysql-connector-python --upgrade

# Comando por defecto
# CMD ["python", "prepare_test_environment.py"]
